Feature/project
YiCChi/time-tracing-api pull request #12
Opened 2022-12-18 02:55 UTC by cyan515

2022-12-18 13:29 UTC, YiCChi requested changes

2022-12-18 13:29 UTC, YiCChi commented on src/project/entities/project.entity.ts
> +  startTime: number;
これと`endTime`のほうは多分、Dateとかにしたほうがいいと思った

2022-12-18 14:58 UTC, cyan515 commented on src/project/entities/project.entity.ts
> +  startTime: number;
となると、属性名もそれぞれ `startDate` `endDate` の方がわかりやすい？

2023-01-04 08:41 UTC, YiCChi commented on src/project/entities/project.entity.ts
> +  startTime: number;
確かに、そうしたほうがいいかも。

2023-01-06 11:17 UTC, cyan515 commented on src/project/entities/project.entity.ts
> +  startTime: number;
修正しました。[b9e1bf0](https://github.com/YiCChi/time-tracing-api/pull/12/commits/b9e1bf0f14065f2a3fa5f0d160f55649d8736b73)

2023-01-06 11:31 UTC, YiCChi approved these changes

2023-01-08 12:21 UTC, merged